<?php
/**
 * @file
 * This is the main module file.
 */

/**
 * Implements hook_help().
 */
function shownodes_help($path, $arg) {

    if ($path == 'admin/help#shownodes') {
        $output = '<h3>' . t('About') . '</h3>';
        $output .= '<p>' . t('The shownodes module allows the Administrator to display various types of nodes as a block on your Drupal site.') . '</p>';
        return $output;
    }
}
/**
* Implements of hook_menu().
*/
function shownodes_menu() {

$items['admin/config/shownodes'] = array(
'title' => t('Choose the nodes to show'),
'description' => t('You can select which node types you want to show'),
'page callback' => 'system_admin_menu_block_page',
'access arguments' => array('administer site configuration'),
'file' => 'system.admin.inc',
'file path' => drupal_get_path('module', 'system'),
);

$items['admin/config/shownodes/settings'] = array(
'title' => t('Choose the nodes to show'),
'description' => t('You can select which node types you want to show'),
'page callback' => 'drupal_get_form',
'page arguments' => array('shownodes_admin_settings'),
'access arguments' => array('administer site configuration'),
'type' => MENU_NORMAL_ITEM,
);

return $items;
}

function shownodes_admin_settings() {

$types = node_type_get_types();
foreach($types as $node_type) {
$nodetypes[$node_type->type] = $node_type->name;
}
dpm($types);
$form['shownodes_nodes_toshow'] = array(
'#type' => 'select',
'#title' => t('Select the nodes to show'),
'#options' => $nodetypes,
'#default_value' => variable_get('shownodes_nodes_toshow', array('')),
'#description' => t('All the node types selected below will be shown'),
);
dpm($nodetypes);
return system_settings_form($form);
}