<?php
/**
 * Created by PhpStorm.
 * User: Sergiu
 * Date: 4/4/14
 * Time: 5:09 PM
 */

function nstat_schema() {
$schema['nstat'] = array(
  'description' => 'Mini Statistics',
  'fields' => array(
    'nid' => array(
      'description' => 'The node ID',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'uid' => array(
      'description' => 'The User ID',
      'type' => 'int',
      'not null' => TRUE,
    ),
    'timestamp' => array(
      'description' => 'The field designated for time storage',
      'type' => 'int',
      'not null' => TRUE,
    ),
  ),
);
  return $schema;
}

function nstat_node_view($node, $view_mode='full', $langcode) {
  global $user;

 if ($view_mode == 'full'){

$nid = db_insert('nstat')
  ->fields(array('nid', 'uid', 'timestamp'))
  ->values(array(
    'nid' => $node->nid,
    'uid' => $user->uid,
    'timestamp' => REQUEST_TIME,
  ))
  ->execute();

  $result = db_query("SELECT * FROM {nstat} WHERE nid = :nid", array(':nid' => $node->nid));
  $record = $result->fetchALL();

  $number_of_rows = $result->rowCount();
  // $number_of_rows = db_select('nstat')->countQuery()->execute()->fetchField();
  //dpm($number_of_rows,'asasd');


//  foreach($result as $data) {
//    $rows[] = array(
//      $data->uid,
//      $data->nid,
//      $data->timestamp,
//    );
//  }
//
//  dpm($number_of_rows,'count');
//  dpm($record,'record');
//  dpm($record[$number_of_rows-2]->uid,'uid');
  //dpm($rows,'row');
  //dpm($result->fetchAll(), 'results');
//$total = 0;
$today = 0;
$today2 = 0;
   foreach ($record as $i => $value){
     $timpul[$i] = gmdate("d-m-Y", $record[$i]->timestamp);
     if ($timpul[$i]== gmdate("d-m-Y",REQUEST_TIME)) $today2++;
   }

  //for($i=0; $i <= $number_of_rows-1; $i++) {
  foreach ($record as $i => $value) {
    //if($record[$i]->nid == $node->nid)$total = $total + 1;
    if($record[$i]->timestamp >= REQUEST_TIME-86400)$today++;
  }
//dpm($today);
  $date = format_date($record[$number_of_rows-2]->timestamp, 'custom', 'd-m-Y H:i');
  //$date_all = format_date($record->timestamp, 'custom', 'd.m.Y');
  //dpm($date_all,'date');


 // dpm($record,'record time');
  dpm($timpul,'timpul');
   dpm($today2,'azi2');
  $uuid = $record[$number_of_rows-2]->uid;
  //dpm($uuid,'uuid');
  $result2 = db_query("SELECT name FROM {users} WHERE uid = :uid", array(':uid' => $uuid));

  $record2 = $result2->fetchall();
  if ($number_of_rows == 1) $userview = 'First View';
  else if ($uuid == 0) $userview = 'Anonymus';
  else $userview = $record2[0]->name;

//dpm($record2);
  $node->content['my_extra_content'] =array(
    '#weight' => -11111,
    '#markup' => t('</br>Last viewed by: <font color ="red">'. $userview .'</font> at '. $date .'</br>Number of viwes: '. $today2 .' today /'.  $number_of_rows . ' total</br>'),
  );

//  $node->content['my_extra_content'] =array(
//    '#weight' => -11111,
//    '#markup' => t('Not Hello')
//  );
 }
}